language: node_js

env:
  - TARGET=travis

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "9"
  - "10"

matrix:
  include:
  - name: Travis main 8.4.0
    node_js: "8.4.0"
    env: TARGET=travis-main
  - name: BrowserStack IE11
    node_js: "8.4.0"
    env: TARGET=test-browserstack-ie11
  - name: Chrome headless
    node_js: "8.4.0"
    env: TARGET=test-chrome-headless

addons:
  chrome: stable

script: make $TARGET
