language: node_js

env:
  - TARGET=travis

node_js:
  - "6"
  - "7"
  - "8.4.0"
  - "9"
  - "10"

matrix:
  include:
  - name: Lint (8.4.0)
    node_js: "8.4.0"
    env: TARGET=lint
  - name: Jest (8.4.0)
    node_js: "8.4.0"
    env: TARGET=test-jest
  - name: Jasmine (8.4.0)
    node_js: "8.4.0"
    env: TARGET=test-jasmine
  - name: Coverage (8.4.0)
    node_js: "8.4.0"
    env: TARGET=travis-coverage
  - name: BrowserStack IE11
    node_js: "8.4.0"
    env: TARGET=test-browserstack-ie11
  - name: Chrome headless
    node_js: "8.4.0"
    env: TARGET=test-chrome-headless

addons:
  chrome: stable

script: make $TARGET
